### ISSUE TITLE
React Link 컴포넌트 사용시 에러

### ISSUE THREAD

**Issue by henniyoon** [henniyoon/guild-manager#27]
Header 제목에 메인 페이지로 가는 링크를 걸기 위해서 Link 컴포넌트를 사용하려고 Header.tsx 파일을 수정했는데 에러 발생
```
import '../style/Header.css';
import { Link } from 'react-router-dom'; // 추가된 부분

const Header = () => {
  return (
    <header className="header">
      <div className="logo">LOGO</div>
      <h1 className="title">
        <Link to="/">Guild Page</Link> // 추가된 부분
      </h1>
      <nav className="nav">
        <a href="/">Home</a>
        <a href="/about">About</a>
        <a href="/services">Services</a>
        <a href="/contact">Contact</a>
      </nav>
    </header>
  );
};

export default Header;
```

```
Uncaught runtime errors:
×
ERROR
Cannot destructure property 'basename' of 'react__WEBPACK_IMPORTED_MODULE_0__.useContext(...)' as it is null.
TypeError: Cannot destructure property 'basename' of 'react__WEBPACK_IMPORTED_MODULE_0__.useContext(...)' as it is null.
    at LinkWithRef (http://localhost:3000/static/js/bundle.js:38563:5)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:25435:22)
    at updateForwardRef (http://localhost:3000/static/js/bundle.js:28004:24)
    at beginWork (http://localhost:3000/static/js/bundle.js:30051:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:15031:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:15075:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:15132:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:34996:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:34244:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:34167:9)
```

GPT 답변
```
이 에러는 react-router-dom의 Link 컴포넌트를 사용할 때 BrowserRouter로 둘러싸여있지 않아서 발생하는 것으로 보입니다.
BrowserRouter 컴포넌트는 Link 컴포넌트가 정상적으로 동작하도록 필요한 컨텍스트를 제공합니다.

해결하기 위해서는 애플리케이션의 최상위 컴포넌트에서 BrowserRouter로 감싸야 합니다. 
```

최상위 컴포넌트에서 BrowserRouter로 감싸야 한다고 해서 App.tsx 파일을 보니
```
import React from 'react';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import Mainpage from './component/Mainpage';
import Guildpage from './component/Guildpage';
import Graphpage from './component/Graphpage';
import Adminpage from './component/Adminpage'

const App: React.FC = () => {
  return (
    <Router>
      <Routes>
        <Route path="/" element={<Mainpage />} />
        <Route path="/Guildpage" element={<Guildpage />} />
        <Route path="/Graphpage" element={<Graphpage />} />
        <Route path="/Adminpage" element={<Adminpage />} />
      </Routes>
    </Router>
  );
};

export default App;
```

이렇게 작성되어 있었는데 이 가장 바깥에 BrowserRouter가 있어야 하나 싶어서

```
<BrowserRouter>
  <Router>
      <Routes>
        <Route path="/" element={<Mainpage />} />
        <Route path="/Guildpage" element={<Guildpage />} />
        <Route path="/Graphpage" element={<Graphpage />} />
        <Route path="/Adminpage" element={<Adminpage />} />
      </Routes>
    </Router>
</BrowserRouter>
```
로 수정해주었더니 또 에러 발생

```
Uncaught runtime errors:
×
ERROR
You cannot render a <Router> inside another <Router>. You should never have more than one in your app.
    at invariant (http://localhost:3000/static/js/bundle.js:1869:11)
    at Router (http://localhost:3000/static/js/bundle.js:40480:103)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:25443:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:28727:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:30023:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:15039:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:15083:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:15140:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:35004:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:34252:16)
```

전과는 다른 에러여서 읽어보니 라우터 안에 또 다른 라우터를 렌더링 할 수 없다는 것 같아서
BrowserRouter 컴포넌트가 Router 컴포넌트의 상위 컴포넌트인가 싶어서 아래와 같이 수정
```
<BrowserRouter>
     <Routes>
       <Route path="/" element={<Mainpage />} />
       <Route path="/Guildpage" element={<Guildpage />} />
       <Route path="/Graphpage" element={<Graphpage />} />
       <Route path="/Adminpage" element={<Adminpage />} />
     </Routes>
</BrowserRouter>
```

했더니 가장 처음 떴던 오류 발생..!

그래서 다시 생각해보니 여기는 App 단에 들어가는 내용이 있는 부분이고 내가 Link 컴포넌트를 사용하고 싶은 Header는 들어있지 않았다!

그리고 index.tsx 파일에서 발견!

```
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import Header from './component/Header';

const root = ReactDOM.createRoot(document.getElementById('root') as HTMLElement);
root.render(
  <React.StrictMode>
    <Header />
    <App />
  </React.StrictMode>
);
```

이렇게 작성되어 있던 코드에 가장 최상단을 BrowserRouter 컴포넌트로 감싸줬다!
```
<React.StrictMode>
    <BrowserRouter>
      <Header />
      <App />
    </BrowserRouter>
  </React.StrictMode>
```

그리고 App.tsx 파일에서는 BrowserRouter 를 삭제해주니 정상적으로 작동 됐다~!
```
import React from 'react';
import { Routes, Route } from 'react-router-dom';
import Mainpage from './component/Mainpage';
import Guildpage from './component/Guildpage';
import Graphpage from './component/Graphpage';
import Adminpage from './component/Adminpage'

const App: React.FC = () => {
  return (
    <Routes>
      <Route path="/" element={<Mainpage />} />
      <Route path="/Guildpage" element={<Guildpage />} />
      <Route path="/Graphpage" element={<Graphpage />} />
      <Route path="/Adminpage" element={<Adminpage />} />
    </Routes>
  );
};

export default App;
```

![image](https://github.com/henniyoon/guild-manager/assets/54562505/8ebbaaa8-1d51-47cd-94aa-d0d507e7d538)

혹시 해결한 방법에 문제가 있다면 알려주세요 은철씨!

**Comment by ChoiEunCheol** [comment]
잘 해결하신 것 같슴당
